{% set version = "3.7.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-choroplethr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/choroplethr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/choroplethr/choroplethr_{{ version }}.tar.gz
  sha256: 116a2b63b2e60787c5f04917e80bb9c6d1dd4f1c9503717d64ea7ad2d0e99cfa

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-hmisc
    - r-r6
    - r-rgooglemaps
    - r-wdi
    - r-acs
    - r-dplyr
    - r-ggmap
    - r-ggplot2 >=2.0.0
    - r-gridextra
    - r-rvest
    - r-stringr
    - r-tidycensus
    - r-tidyr
    - r-tigris >=1.0
    - r-xml2
  run:
    - r-base
    - r-hmisc
    - r-r6
    - r-rgooglemaps
    - r-wdi
    - r-acs
    - r-dplyr
    - r-ggmap
    - r-ggplot2 >=2.0.0
    - r-gridextra
    - r-rvest
    - r-stringr
    - r-tidycensus
    - r-tidyr
    - r-tigris >=1.0
    - r-xml2

test:
  commands:
    - $R -e "library('choroplethr')"           # [not win]
    - "\"%R%\" -e \"library('choroplethr')\""  # [win]

about:
  home: www.choroplethr.com
  license: BSD-3-Clause
  summary: Choropleths are thematic maps where geographic regions, such as states, are colored according to some metric, such as the number of people who live in that state. This package simplifies this process by 1. Providing ready-made functions for creating choropleths of common maps. 2. Providing data and API connections
    to interesting data sources for making choropleths. 3. Providing a framework for creating choropleths from arbitrary shapefiles. 4. Overlaying those maps over reference maps from Google Maps.
  license_family: BSD
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/BSD_3_clause
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - izahn
